name: fire_statex
description: "A flutter state management basics"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  faker: ^2.1.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  path_provider: ^2.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  objectbox_generator: any

flutter:
  uses-material-design: true

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  # output_dir: custom
  # Or optionally specify the lib and test output folder separately.
  output_dir:
    lib: data
    test: test/models/